paths:
  /api/products:
    get:
      tags:
        - Products
      summary: Este end Point permite acceder a la lista de productos
      description: Lista de productos 
      responses:
        "200":
          description: successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de conexion con la base de datos
    post:
      tags:
        - Products
      summary: Add a new product to the store
      description: Add a new product to the store
      operationId: addProduct
      requestBody:
        description: Create a new Product in the store
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  required: true
                description:
                  type: string
                  required: true
                code: 
                  type: string
                  required: true
                  unique: true
                price:
                  type: number
                  required: true
                status:
                  type: boolean
                  required: true
                stock:
                  type: number
                  required: true
                category: 
                  type: string
                  required: true
                  defaault: 'No Catgory'
                thumbnail: 
                  type: array
                owner:
                  type: string
                  required: true,
                  default: 'admin'
              $ref: '#/components/schemas/Product'
      responses:
        "200":
          description: succefull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "401":
          description: 'Token missing, Unauthorized!'
        "500":
          description: 'Error interno del servidor, usualmente generado por una query defectuosa o un fallo de conexion con la base de datos'
  /api/products/{pid}:
    get:
      tags:
        - Products
      summary: Find Product by Id
      description: Return a single product
      parameters:
        - name: pid
          in: path
          description: ID product to return
          required: true
          schema:
            type: string
      responses:
        "201":
          description: successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "400":
          description: Invalid ID supplied
    put:
      tags:
        - Products
      summary: Update Product by Id
      description: Update a single product
      parameters:
        - name: pid
          in: path
          description: ID product to update
          required: true
          schema:
            type: string
      responses:
        "201":
          description: successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "400":
          description: Invalid ID supplied
    delete:
      tags:
        - Products
      summary: Delete Product by Id
      description: Delete a single product
      parameters:
        - name: pid
          in: path
          description: ID product to delete
          required: true
          schema:
            type: string
      responses:
        "201":
          description: successfull operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "400":
          description: Invalid ID supplied
    
components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          required: true
        description:
          type: string
          required: true
        code: 
          type: string
          required: true
          unique: true
        price:
          type: number
          required: true
        status:
          type: boolean
          required: true
        stock:
          type: number
          required: true
        category: 
          type: string
          required: true
          defaault: 'No Catgory'
        thumbnail: 
          type: array
        owner:
          type: string
          required: true,
          default: 'admin'
      example:
        _id: ObjectId('657f088bbf51d6bc5c0353b3')
        title: title 1 Update
        description: description 1 Update
        price: 123456
        thumbnail: []
        code: 1111
        stock: 123
        category: category 1
        status: true
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT